
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.115.21.244:3306/content_center?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
        discovery:
          server-addr: localhost:8848
          metadata:
            # 自己这个实例的版本
            version: v1
            # 允许调用的提供者版本
            target-version: v1
          cluster-name: JX
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: false
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  application:
      name: content-centon
  main:
    allow-bean-definition-overriding: true
server:
  port: 9091

#配置属性配置负载均衡ribbon
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eager-load:
#    #开启饥饿加载
#    enabled: true
#    clients: user-center

ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.example.contentcenter.feignClient.UserCenterFeignClient: debug
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#暴露sentnel端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 设置成false，表示关闭@SentinelRestTemplate注解
    enabled: false